// c:\codes\vasd\lib\features\package_info.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:

export 'view/view.dart';
export 'widgets/widgets.dart';
