// c:\codes\vasd\lib\repositories\additional_func.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:

export 'models/models.dart';
export 'additional_func_local_repo.dart';